### ISSUE TITLE
setup.py fails on blas_info['libraries']

### ISSUE THREAD

**Issue by tvandera** [untom/binet#1]
It seems the 'libraries' key is not available in blas_info:

Content of blas_info:
`{'extra_link_args': ['-Wl,-framework', '-Wl,Accelerate'], 'extra_compile_args': ['-msse3', '-DAPPLE_ACCELERATE_SGEMV_PATCH', '-I/System/Library/Frameworks/vecLib.framework/Headers'], 'define_macros': [('NO_ATLAS_INFO', 3)]}`

Error message:

```
Traceback (most recent call last):
  File "setup.py", line 56, in <module>
    libraries=blas_info['libraries'],
KeyError: 'libraries'
```

Python 2.7.11 on Mac OS X using Homebrew

**Comment by untom** [comment]
Thanks for reporting this. I never tried binet on Mac OS before. As a quick hack, you could replace lines 54-58:

    ext_modules = cythonize([Extension("binet.op", ["binet/op.pyx"],
              libraries=blas_info['libraries'],
              library_dirs=blas_info.get('library_dirs', []),
              include_dirs=[np.get_include()] + blas_info.get('include_dirs', []),
              )

with these lines:

    ext_modules = cythonize([Extension("binet.op", ["binet/op.pyx"],
              libraries=blas_info['extra_link_args'],
              library_dirs=blas_info.get('library_dirs', []),
              include_dirs=[np.get_include()] + ['/System/Library/Frameworks/vecLib.framework/Headers']),
              )


I'll try to find a better fix for future versions.

**Comment by untom** [comment]
Could you also please run the following code on your system and tell me the output:

    import numpy as np
    np.__config__.show()

**Comment by tvandera** [comment]
The following seems to work (although there must be a cleaner way to do this):

```
    ext_modules = cythonize([Extension("binet.op", ["binet/op.pyx"],
              libraries=blas_info.get('libraries', []),
              extra_link_args=blas_info.get('extra_link_args', []),
              extra_compile_args=blas_info.get('extra_compile_args', []) + ['-Wno-unused-function'],
              define_macros=blas_info.get('define_macros', []),
              library_dirs=blas_info.get('library_dirs', []),
              include_dirs=[np.get_include()] + blas_info.get('include_dirs', []),

              )
    ]),
```

`numpy.__config__`:

```
Python 2.7.11 (default, Dec  5 2015, 14:44:53)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__config__.show()
lapack_opt_info:
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    extra_compile_args = ['-msse3']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
openblas_lapack_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blas_opt_info:
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
atlas_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
mkl_info:
  NOT AVAILABLE
```

**Comment by untom** [comment]
Thanks, this has worked nicely!
